### ISSUE TITLE
Is the get function reactive?

### ISSUE THREAD

**Issue by dalgard** [chuangbo/meteor-cookie#7]
Is the get function reactive?

**Comment by dalgard** [comment]
Sorry, I see from the code that reactivity is not part of it. I guess that's fine, since it wouldn't capture 3rd party updates to `document.cookie`, anyway – but it should probably be mentioned in the doc. Thanks.

**Comment by chuangbo** [comment]
Sorry no. Just a wapper for a simple cookie library.
